# Netlify configuration for Next.js 16 with API routes and middleware

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Enable Next.js Runtime for serverless functions and middleware
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect rules for Next.js routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = false

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables to configure in Netlify Dashboard:
# NEXTAUTH_URL=https://yourdomain.netlify.app
# NEXTAUTH_SECRET=your-secret-key
# ADMIN_EMAIL=admin@renewedpower.com
# ADMIN_PASSWORD=your-secure-password
# DATABASE_URL=your-supabase-database-url
# NEXT_PUBLIC_SUPABASE_URL=your-supabase-url
# NEXT_PUBLIC_SUPABASE_ANON_KEY=your-supabase-anon-key
